#!/usr/bin/env bash
# This script transfers a file from our client to a server

# Check number of arguments
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign variables
FILE=$1
IP=$2
USERNAME=$3
KEY=$4

# Use scp to transfer the file
scp -i "$KEY" -o StrictHostKeyChecking=no "$FILE" "$USERNAME"@"$IP":~/

# Check if file transfer was successful
if [$? -eq 0]; then
	echo "File Transfer Completed"
else
	echo "File Transfer Failed"
fi
