#!/usr/bin/env bash
# Install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Start nginx
sudo service nginx start

# Create a configuration snippet to handle the redirection
echo 'server {
    listen 80;
    server_name localhost;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}' | sudo tee /etc/nginx/sites-available/redirection

# Enable the configuration by creating a symbolic link
sudo ln -s /etc/nginx/sites-available/redirection /etc/nginx/sites-enabled/

# Remove the default configuration
sudo rm /etc/nginx/sites-enabled/default

# Reload the nginx service to apply the changes
sudo service nginx reload
