#!/usr/bin/env bash
# Install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Start nginx
sudo service nginx start

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Create a configuration snippet to handle the 404 error
echo 'server {
    listen 80;
    server_name localhost;
    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /var/www/html;
        internal;
    }
}' | sudo tee /etc/nginx/sites-available/custom_404

# Enable the configuration by creating a symbolic link
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Remove the default configuration
sudo rm /etc/nginx/sites-enabled/default

# Reload the nginx service to apply the changes
sudo service nginx reload
