#!/usr/bin/env bash
# Configuring the server to enable nginx running on 80 port

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid