#!/usr/bin/env bash
# This script processes /etc/passwd to generate a story-based output

while IFS=: read -r username password uid gid user_info homedir shell; do
    echo "The user $username is part of the $uid gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd
