#!/usr/bin/env bash
# This script parses the Apache access log, groups by IP and HTTP
# status code, and orders the data by occurrence

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr
