#!/usr/bin/env bash
# Change your home IP

# Create a new copy of /etc/hosts in home directory
cp /etc/hosts ~/hosts.new

# Modify localhost entry in the new hosts file
sed -i 's/^127.0.0.1.*/127.0.0.2 localhost/g' ~/hosts.new

# Add facebook.com entry to the new hosts file
echo "8.8.8.8 facebook.com" >> ~/hosts.new

# Replace original /etc/hosts file with the modified one
cp -f ~/hosts.new /etc/hosts
